name: rag_env
channels:
  - conda-forge
  - nodefaults
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - accelerate=1.10.0
  - aiofiles=24.1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - alsa-lib=1.2.14
  - altair=5.5.0
  - annotated-types=0.7.0
  - anyio=4.10.0
  - aom=3.9.1
  - arrow=1.3.0
  - attr=2.5.1
  - attrs=25.3.0
  - aws-c-auth=0.8.6
  - aws-c-cal=0.8.7
  - aws-c-common=0.12.0
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.4
  - aws-c-io=0.17.0
  - aws-c-mqtt=0.12.2
  - aws-c-s3=0.7.13
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.3
  - aws-crt-cpp=0.31.0
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - binaryornot=0.4.4
  - blinker=1.9.0
  - bm25s=0.2.13
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cachetools=6.1.0
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.3
  - click=8.2.1
  - colorama=0.4.6
  - contourpy=1.3.3
  - cookiecutter=2.6.0
  - cpython=3.13.5
  - cuda-crt-tools=12.9.86
  - cuda-cudart=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-cuobjdump=12.9.82
  - cuda-cupti=12.9.79
  - cuda-nvcc-tools=12.9.86
  - cuda-nvdisasm=12.9.88
  - cuda-nvrtc=12.9.86
  - cuda-nvtx=12.9.79
  - cuda-nvvm-tools=12.9.86
  - cuda-version=12.9
  - cudnn=9.11.0.98
  - cusparselt=0.7.0.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dataclasses=0.8
  - datasets=2.2.1
  - dav1d=1.2.1
  - dbus=1.16.2
  - dill=0.4.0
  - dnspython=2.7.0
  - double-conversion=3.3.1
  - email-validator=2.2.0
  - email_validator=2.2.0
  - evaluate=0.4.5
  - exceptiongroup=1.3.0
  - fastapi=0.116.1
  - fastapi-cli=0.0.8
  - fastapi-core=0.116.1
  - ffmpeg=7.1.1
  - ffmpy=0.3.0
  - filelock=3.19.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.7.0
  - fsspec=2025.7.0
  - gdk-pixbuf=2.42.12
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gradio=3.24.1
  - gradio-client=1.11.1
  - graphite2=1.3.14
  - grpcio=1.67.1
  - grpcio-tools=1.67.1
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=11.4.1
  - hf-xet=1.1.8
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.6.4
  - httpx=0.28.1
  - huggingface_hub=0.34.4
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - jinja2=3.1.6
  - joblib=1.5.1
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.4.1
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - level-zero=1.24.1
  - libabseil=20240722.0
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.3
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.75
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.8
  - libclang13=20.1.8
  - libcrc32c=1.1.2
  - libcublas=12.9.1.4
  - libcudnn=9.11.0.98
  - libcudnn-dev=9.11.0.98
  - libcudss0=0.4.0.2
  - libcufft=11.4.1.4
  - libcufile=1.14.1.1
  - libcups=2.3.3
  - libcurand=10.3.10.19
  - libcurl=8.14.1
  - libcusolver=11.7.5.82
  - libcusparse=12.5.10.65
  - libde265=1.0.15
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgpg-error=1.55
  - libgrpc=1.67.1
  - libheif=1.19.7
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - libmagma=2.8.0
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libntlm=1.8
  - libnvjitlink=12.9.86
  - libnvjpeg=12.4.0.76
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.18.0
  - libopentelemetry-cpp-headers=1.18.0
  - libopenvino=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-intel-gpu-plugin=2025.0.0
  - libopenvino-intel-npu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.5.2
  - libparquet=19.0.1
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.7
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libudev1=257.7
  - libunwind=1.8.2
  - liburing=2.11
  - libusb=1.0.29
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libuv=1.51.0
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - linkify-it-py=2.0.3
  - lz4-c=1.10.0
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib=3.10.5
  - matplotlib-base=3.10.5
  - mdit-py-plugins=0.3.3
  - mdurl=0.1.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - multidict=6.6.3
  - multiprocess=0.70.18
  - munkres=1.1.4
  - narwhals=2.1.2
  - nccl=2.27.7.1
  - ncurses=6.5
  - networkx=3.5
  - nlohmann_json=3.12.0
  - nomkl=1.0
  - numpy=2.3.2
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.2
  - optree=0.17.0
  - orc=2.1.1
  - orjson=3.11.2
  - packaging=25.0
  - pandas=2.3.2
  - pango=1.56.4
  - patsy=1.0.1
  - pcre2=10.45
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - portalocker=2.10.1
  - prometheus-cpp=1.3.0
  - propcache=0.3.1
  - protobuf=5.28.3
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pybind11=3.0.0
  - pybind11-global=3.0.0
  - pycparser=2.22
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pydeck=0.9.1
  - pydub=0.25.1
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pyside6=6.9.1
  - pysocks=1.7.1
  - python=3.13.5
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-gil=3.13.5
  - python-multipart=0.0.20
  - python-slugify=8.0.4
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.13
  - pytorch=2.6.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - qdrant-client=1.15.1
  - qhull=2020.2
  - qt6-main=6.9.1
  - rav1e=0.7.1
  - rdma-core=58.0
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.36.2
  - regex=2025.7.34
  - requests=2.32.5
  - responses=0.18.0
  - rich=14.1.0
  - rich-toolkit=0.15.0
  - rpds-py=0.27.0
  - s2n=1.5.14
  - safetensors=0.6.2
  - scikit-learn=1.7.1
  - scipy=1.16.1
  - sdl2=2.32.54
  - sdl3=3.2.20
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - semantic_version=2.10.0
  - sentence-transformers=5.1.0
  - setuptools=80.9.0
  - shellingham=1.5.4
  - six=1.17.0
  - sleef=3.8
  - smmap=5.0.2
  - snappy=1.2.2
  - sniffio=1.3.1
  - starlette=0.47.2
  - statsmodels=0.14.5
  - streamlit=1.48.1
  - svt-av1=3.0.2
  - sympy=1.14.0
  - tabulate=0.9.0
  - tbb=2022.2.0
  - tenacity=9.1.2
  - text-unidecode=1.3
  - threadpoolctl=3.6.0
  - timm=1.0.19
  - tk=8.6.13
  - tokenizers=0.21.4
  - toml=0.10.2
  - torchvision=0.21.0
  - torchvision-extra-decoders=0.0.2
  - tornado=6.5.2
  - tqdm=4.67.1
  - transformers=4.55.4
  - triton=3.2.0
  - typer=0.16.1
  - typer-slim=0.16.1
  - typer-slim-standard=0.16.1
  - types-python-dateutil=2.9.0.20250822
  - typing-extensions=4.14.1
  - typing-inspection=0.4.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - uc-micro-py=1.0.3
  - urllib3=2.5.0
  - uvicorn=0.35.0
  - uvicorn-standard=0.35.0
  - uvloop=0.21.0
  - watchdog=6.0.0
  - watchfiles=1.1.0
  - wayland=1.24.0
  - wayland-protocols=1.45
  - websockets=15.0.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xxhash=0.8.3
  - yaml=0.2.5
  - yarl=1.20.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - sortedcontainers==2.4.0
